#!/bin/bash

function has_command {
  command -v $1 >/dev/null 2>&1;
}

function install_brew {
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
}

if has_command "brew"; then
  echo "Brew already installed"
else
  echo "Installing brew"
  install_brew
fi

echo

current_dir="$(dirname $(realpath $0))"

echo "Installing from Brewfile.main"
brew bundle --file "$current_dir/Brewfile.main"
echo

echo "Installing from Brewfile.work"
brew bundle --file "$current_dir/Brewfile.work"
echo

echo "Installing from Brewfile.personal"
brew bundle --file "$current_dir/Brewfile.personal"
