#!/usr/bin/env sh

echo "Disable font smoothing on non-Apple LCDs"
# defaults write NSGlobalDomain CGFontRenderingFontSmoothingDisabled -bool NO
defaults -currentHost write -g AppleFontSmoothing -int 0

echo "Enable full keyboard access for all controls (e.g. enable Tab in modal dialogs)"
defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

echo "Allow quitting Finder via ⌘ + Q; doing so will also hide desktop icons"
defaults write com.apple.finder QuitMenuItem -bool true

echo "Show all filename extensions in Finder"
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

echo "Use current directory as default search scope in Finder"
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

echo "Show Path bar in Finder"
defaults write com.apple.finder ShowPathbar -bool true

echo "Show Status bar in Finder"
defaults write com.apple.finder ShowStatusBar -bool true

echo "Expand save panel by default"
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true

echo "Expand print panel by default"
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true

echo "Disable press-and-hold for keys in favor of key repeat"
defaults write -g ApplePressAndHoldEnabled -bool false

echo "Set a shorter delay until key repeat"
defaults write -g InitialKeyRepeat -int 10

echo "Set quick key repeat"
defaults write -g KeyRepeat -int 2

# echo "Enable AirDrop over Ethernet and on unsupported Macs running Lion"
# defaults write com.apple.NetworkBrowser BrowseAllInterfaces -bool true

echo "Avoid creating .DS_Store files on network volumes"
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

echo "Disable the warning when changing a file extension"
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

echo "Show the ~/Library folder"
chflags nohidden ~/Library

echo "Set dock to left side of the screen"
defaults write com.apple.dock orientation left

echo "Enable dock autohiding"
defaults write com.apple.dock "autohide" -bool "true"

echo "Clear all dock apps"
defaults write com.apple.dock persistent-apps -array

echo "Enable keyboard navigation of prompts"
defaults write -g AppleKeyboardUIMode -int 2

echo "Enable tap to click"
defaults write com.apple.AppleMultitouchTrackpad Clicking -bool true
sudo defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
sudo defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
sudo defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1

echo "Setup mission control bottom right hot corner"
defaults write com.apple.dock wvous-br-corner -int 2
defaults write com.apple.dock wvous-br-modifier -int 0

echo "Set screenshot location to Pictures/Screenshots"
mkdir ~/Pictures/Screenshots
defaults write com.apple.screencapture "location" -string "~/Pictures/Screenshots" && killall SystemUIServer

echo "Disable screenshot thumbnail"
defaults write com.apple.screencapture "show-thumbnail" -bool "false"

echo "Show the ~/Library folder"
chflags nohidden ~/Library

echo "Use list view in all Finder windows by default"
# Four-letter codes for the other view modes: `icnv`, `clmv`, `Flwv`
defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

echo "Kill affected applications"
for app in Finder Dock SystemUIServer; do killall "$app" >/dev/null 2>&1; done
